title: ruolan
author: © 2018 ruolan. Powered by github & Jekyll
email: ruolan8@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
paginate: 10

# social links
linkedin_username: ruolanhuang
github_username: ruolan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
#
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - project.md
  - design.md
  - blog.md
  - about.md

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
